<?php // echo $this->headTitle("order")          ?>
<?php // $this->headLink()->appendStylesheet('/css/main.css')         ?>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<?php $this->headScript()->appendFile('/cafee-helper/js/mychecks.js'); ?>


<br /><br /> 
<div id='myorderss'> 

    <p>start Date: <input type="text" id="startdatepicker"></p>
    <p>end Date: <input type="text" id="enddatepicker"></p>
    <div id="users" >
            <label>Add to user</label><br>
            <select id="selectuser" name='user'>
                <?php
                for ($i = 1; $i < count($this->users); $i++) {
                    $name = $this->users[$i]['name'];
                    $id = $this->users[$i]['id'];
                    ?>
                    <option value='<?php echo $id ;?>'><?php echo $name; ?></option>
                <?php } ?>
            </select>
        </div>
    <input type="button" id="myorders" value="my orders"/>

    <div id="checks">

        <table border='2'  style="size: auto" style="border-color: cadetblue" id='opt'>
            <th> Date </th><th> Price</th>
            <?php for ($i = 0; $i < count($this->checks); $i++) { ?>
                <tr>

                    <td class='myname' id='<?php echo $this->checks[$i]['u_id']; ?>' > 
                        <?php // for    ($j = 0; $j < count($this->latestorder[0]); $i++) { ?>

                        <?php echo $this->checks[$i]['user_name']; ?>

                    </td> 

                     <td > 
                        <?php // for ($j = 0; $j < count($this->latestorder[0]); $i++) { ?>

                        <?php echo $this->checks[$i]['total_price']; ?>


                    </td> 

                </tr>





            <?php } ?> 



        </table> 
    </div>
    
    
    
    <div id="myuserdates">
       
        <table border='2'  style="size: auto" style="border-color: cadetblue" id='mydetails'>
          


            <?php for ($i = 0; $i < count($this->mydates); $i++) { ?>
                <tr>

                    <td  class='mydate' id='<?php echo $this->mydates[$i]['id']; ?>'> 
                        <?php // for ($j = 0; $j < count($this->latestorder[0]); $i++) { ?>

                        <?php echo $this->mydates[$i]['date']; ?>


                    </td> 
                    
                    <td  > 
                        <?php // for ($j = 0; $j < count($this->latestorder[0]); $i++) { ?>

                        <?php echo $this->mydates[$i]['total_price']; ?>


                    </td> 

                    

                </tr>

            <?php } ?> 
                
                
                
                

        </table> 
    </div>
    
    
    
    
    <div id="alldetails">

        <table border='2'  style="size: auto" style="border-color: cadetblue" id='myalldetails'>
          


            <?php for ($i = 0; $i < count($this->myprodorders); $i++) { ?>
                <tr>

                    <td  > 
                        <?php // for ($j = 0; $j < count($this->latestorder[0]); $i++) { ?>

                        <?php echo $this->myprodorders[$i]['prod_name']; ?>


                    </td> 

                     <td> 
                        <?php // for ($j = 0; $j < count($this->latestorder[0]); $i++) { ?>

                        <?php echo $this->myprodorders[$i]['amount']; ?>
                      <img  src="<?php echo $this->baseUrl() . '/img/product/' . $this->myprodorders[$i]['picture']; ?>" alt="product"/>

                    </td> 

                </tr>

            <?php } ?> 

        </table> 
    </div>
</div>